import { Button } from "@repo/ui/button";
import Text from "@/components/atoms/text";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Home",
	description: "Generated by create next app",
};

export default function Home() {
	return (
		<main>
			<Text h3>helo</Text>
			<Button isDisabled={false} variant="primary">
				hello
			</Button>

			<h1>hello</h1>
		</main>
	);
}
